#!/bin/bash
cd $1
echo looking for $1.cue
ls $1.cue
{
if [ ! -f *.cue ]; then
    echo "File not found!"
    exit 0
fi
}

# Slice it up
../slicr $1.cue
cd ..

# Make some mp3s
# shn2mp3 -b 256 $1.flac16

done
